# Generated by Django 5.2.6 on 2025-09-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WikiActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wiki", models.CharField(max_length=50)),
                ("editcount", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="challenge.participant",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "wiki")},
            },
        ),
    ]
