# Generated by Django 5.2.6 on 2025-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiactivity",
            name="ar_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wikiactivity",
            name="rev_count",
            field=models.IntegerField(default=0),
        ),
    ]
