# Generated by Django 4.2.24 on 2025-09-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_wikiactivity_ar_count_wikiactivity_rev_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiactivity',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
